Update build.yml
Signed-off-by: Wesley de Groot <email@wesleydegroot.nl>

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -173,8 +173,29 @@ jobs:
 
       - name: Make Release Dmg
         run: |
-          hdiutil create "Aurora Editor 1.0.dmg" -ov -volname "Aurora Editor" -fs HFS+ -srcfolder "builds/"
-          hdiutil convert "Aurora Editor 1.0.dmg" -format UDZO -o RecitalInstall.dmg
+          hdiutil create temp.dmg -ov -volname "Aurora Editor" -fs HFS+ -srcfolder "builds/"
+          hdiutil convert temp.dmg -format UDZO -o "Aurora Editor 1.0.dmg"
+          
+          IDENTITIES=`/usr/bin/security find-identity -v -p codesigning`
+          
+          if [[ "$IDENTITIES" == *"Developer ID Application:"* ]]; then
+              IDENTITY="Developer ID Application"
+          elif [[ "$IDENTITIES" == *"Mac Developer:"* ]]; then
+              IDENTITY="Mac Developer"
+          elif [[ "$IDENTITIES" == *"Apple Development:"* ]]; then
+              IDENTITY="Apple Development"
+          else
+              echo "Not identity found {$IDENTITIES}"
+          fi
+
+          if [[ "$IDENTITY" != "" ]]; then
+              SIGN=`/usr/bin/codesign "Aurora Editor 1.0.dmg" --display --verbose=2`
+
+              if [[ "$SIGN" != *"Authority="* ]]; then
+                  echo "Signing failed"
+                  # exit 1
+              fi
+          fi
 
       - name: Notarize and Log
         run: |
